Update php sdk to 1.4.1
TransbankDevelopers/transbank-plugin-virtuemart-onepay pull request #6
Opened 2018-10-29 14:14 UTC by vutreras

2018-10-29 14:25 UTC, RodrigoAyala submitted a review, later dismissed

2018-10-30 15:44 UTC, leosoto requested changes

2018-10-30 15:44 UTC, leosoto commented on CHANGELOG.md
> +- Se actualiza sdk js a versión 1.5.8
Please put something the users will understand on the CHANGELOG.

2018-10-30 23:00 UTC, leosoto approved these changes

2018-10-31 11:57 UTC, merged